/* ============================================================
   Creatique Technologies — Polyplastics Solution
   Content parser — turns the plain-text file (js/modules-content.js)
   into the MODULES array used by main.js and module.js.

   BA-facing format is documented in BA-CONTENT-GUIDE.md.
   Do not edit this file to change module/step content — edit
   js/modules-content.js instead.
   ============================================================ */

function parseModulesText(text) {
  const rawLines = String(text).replace(/\r\n/g, "\n").split("\n");
  const n = rawLines.length;
  let i = 0;

  function nextMeaningfulIndex() {
    while (i < n) {
      const t = rawLines[i].trim();
      if (t === "" || t.charAt(0) === "#") { i++; continue; }
      return t;
    }
    return null;
  }

  function matchKV(line) {
    const m = line.match(/^([A-Za-z][A-Za-z ]*):\s?(.*)$/);
    if (!m) return null;
    return { key: m[1].trim(), value: m[2] };
  }

  function readList() {
    const items = [];
    while (true) {
      const t = nextMeaningfulIndex();
      if (t === null || t.charAt(0) !== "-") break;
      items.push(t.slice(1).trim());
      i++;
    }
    return items;
  }

  function parseBranch(value, type, target) {
    const parts = value.split("|");
    const label = (parts[0] || "").trim();
    const text = parts.slice(1).join("|").trim();
    target.branches = target.branches || [];
    target.branches.push({ type, label, text });
  }

  function parseLinksList(target) {
    const items = readList();
    target.links = items.map(item => {
      const parts = item.split("|").map(p => p.trim());
      const l = { href: parts[0], label: parts[1] };
      if (parts[2] && /^secondary$/i.test(parts[2])) l.secondary = true;
      return l;
    });
  }

  function parseStep() {
    const s = {};
    while (true) {
      const t = nextMeaningfulIndex();
      if (t === null) throw new Error("STEP is missing its END STEP line.");
      if (/^END\s+STEP\s*$/i.test(t)) { i++; break; }
      const kv = matchKV(t);
      if (!kv) { i++; continue; }
      i++;
      switch (kv.key.toLowerCase()) {
        case "icon": s.icon = kv.value; break;
        case "phase": s.phase = kv.value; break;
        case "group": s.group = kv.value; break;
        case "title": s.title = kv.value; break;
        case "text": s.text = kv.value; break;
        case "outcome": s.outcome = kv.value; break;
        case "sap": s.sap = /^y(es)?$/i.test(kv.value.trim()); break;
        case "features": s.features = readList(); break;
        default: break;
      }
    }
    return s;
  }

  function parseCycle() {
    const c = {};
    while (true) {
      const t = nextMeaningfulIndex();
      if (t === null) throw new Error("CYCLE is missing its END CYCLE line.");
      if (/^END\s+CYCLE\s*$/i.test(t)) { i++; break; }
      const kv = matchKV(t);
      if (!kv) { i++; continue; }
      i++;
      const key = kv.key.toLowerCase();
      switch (key) {
        case "icon": c.icon = kv.value; break;
        case "actor": c.actor = kv.value; break;
        case "actoricon": c.actorIcon = kv.value; break;
        case "group": c.group = kv.value; break;
        case "title": c.title = kv.value; break;
        case "text": c.text = kv.value; break;
        case "sap": c.sap = /^y(es)?$/i.test(kv.value.trim()); break;
        case "chips": c.chips = readList(); break;
        case "links": parseLinksList(c); break;
        case "branch ok": parseBranch(kv.value, "ok", c); break;
        case "branch no": parseBranch(kv.value, "no", c); break;
        default: break;
      }
    }
    return c;
  }

  function parseDfd() {
    const collected = [];
    while (i < n) {
      const raw = rawLines[i];
      if (raw.trim().toUpperCase() === "END DFD") { i++; return collected.join("\n"); }
      collected.push(raw);
      i++;
    }
    throw new Error("DFD block is missing its END DFD line.");
  }

  function parseSubmodule(id) {
    const sm = { id };
    const cycle = [];
    while (true) {
      const t = nextMeaningfulIndex();
      if (t === null) throw new Error(`SUBMODULE ${id} is missing its END SUBMODULE line.`);
      if (/^END\s+SUBMODULE\s*$/i.test(t)) { i++; break; }
      if (/^CYCLE\s*$/i.test(t)) { i++; cycle.push(parseCycle()); continue; }
      const kv = matchKV(t);
      if (kv) {
        i++;
        switch (kv.key.toLowerCase()) {
          case "icon": sm.icon = kv.value; break;
          case "name": sm.name = kv.value; break;
          case "short": sm.short = kv.value; break;
          default: break;
        }
        continue;
      }
      i++;
    }
    if (cycle.length) sm.cycle = cycle;
    return sm;
  }

  function parseModule(id) {
    const mod = { id };
    const steps = [], submodules = [], cycle = [];
    let dfd = null;
    while (true) {
      const t = nextMeaningfulIndex();
      if (t === null) throw new Error(`MODULE ${id} is missing its END MODULE line.`);
      if (/^END\s+MODULE\s*$/i.test(t)) { i++; break; }
      if (/^STEP\s*$/i.test(t)) { i++; steps.push(parseStep()); continue; }
      const smMatch = t.match(/^SUBMODULE\s+(\d+)\s*$/i);
      if (smMatch) { i++; submodules.push(parseSubmodule(parseInt(smMatch[1], 10))); continue; }
      if (/^CYCLE\s*$/i.test(t)) { i++; cycle.push(parseCycle()); continue; }
      if (/^DFD\s*$/i.test(t)) { i++; dfd = parseDfd(); continue; }
      const kv = matchKV(t);
      if (kv) {
        i++;
        switch (kv.key.toLowerCase()) {
          case "icon": mod.icon = kv.value; break;
          case "name": mod.name = kv.value; break;
          case "short": mod.short = kv.value; break;
          case "desc": mod.desc = kv.value; break;
          default: break;
        }
        continue;
      }
      i++;
    }
    if (steps.length) mod.steps = steps;
    if (submodules.length) mod.submodules = submodules;
    if (cycle.length) mod.cycle = cycle;
    if (dfd !== null) mod.dfd = dfd;
    return mod;
  }

  const modules = [];
  while (true) {
    const t = nextMeaningfulIndex();
    if (t === null) break;
    const mMatch = t.match(/^MODULE\s+(\d+)\s*$/i);
    if (mMatch) { i++; modules.push(parseModule(parseInt(mMatch[1], 10))); continue; }
    i++;
  }
  return modules;
}

// In the browser, js/modules-content.js (loaded just before this file) defines
// MODULES_TEXT — parse it once into the MODULES array main.js/module.js use.
const MODULES = parseModulesText(typeof MODULES_TEXT !== "undefined" ? MODULES_TEXT : "");

if (typeof module !== "undefined" && module.exports) {
  module.exports = { parseModulesText };
}
